# ERROR CHECK CONFIG
#------------------------
#   To check if a field exists and is not none or empty use.
#   Ie. INDIVIDUALNAME: True, to not check change to False

#   To check if a field is a particular field use the field in
#   quotes. Ie.  INDIVIDUALNAME: "Omit"

#   To check if a field is in a range of values use the same as
#   a single field inside brackets. Ie. INDIVIDUALNAME: ["omit", "Omit"]

#   To check if a field exists or is in a range of values ONLY if it exists
#   add "NONE" to check if not inside the brackets.
#   Ie. INDIVIDUALNAME: ["omit", "NONE"]
#   Adding "EMPTY" will also ignore if there are empty tags existing.

#------------------------

# Address Fields (1 - Metadata 'Contact',  2 - Resource 'PointOfContact'.)
# True/ False or Values allowed
INDIVIDUALNAME1: ["Omit", "omit"]
INDIVIDUALNAME2: ["Omit", "omit"]

# True/ False or Values allowed
ORGANISATIONNAME1: "LINZ - Land Information New Zealand"
ORGANISATIONNAME2: "LINZ - Land Information New Zealand"

# True/ False or Values allowed
POSITIONNAME1: True
POSITIONNAME2: True

# True/ False or Values allowed
VOICE1: ["0800 665 463 or +64 4 460 0110", "04 4600110"]
VOICE2: ["0800 665 463 or +64 4 460 0110", "04 4600110"]

# True/ False or Values allowed
FACSIMILE1: False
FACSIMILE2: False

# True/ False or Values allowed
DELIVERYADDRESS1: "155 The Terrace"
DELIVERYADDRESS2: "155 The Terrace"

# True/ False or Values allowed
CITY1: "Wellington"
CITY2: "Wellington"

# True/ False or Values allowed
COUNTRY1: "New Zealand"
COUNTRY2: "New Zealand"

# True/ False or Values allowed
POSTALCODE1: ["6011", "6145"]
POSTALCODE2: ["6011", "6145"]

# True/ False or Values allowed
EMAIL1: ["info@linz.govt.nz", "customersupport@linz.govt.nz"]
EMAIL2: ["info@linz.govt.nz", "customersupport@linz.govt.nz"]

# True/ False or Values allowed
ROLE1: "resourceProvider"
ROLE2: "pointOfContact"

#------------------------

# Hierarchy Level
# True/ False or Values allowed
HIERARCHYLEVEL: "dataset"
HIERARCHYLEVELNAME: "dataset"
SCOPELEVEL: "dataset"
SCOPELEVELDESC: "dataset"

#------------------------
# True/ False or Values allowed
# Security Classification - Resource
SECURITYCLASSRES: "unclassified"
# Security Classification - Metadata
SECURITYCLASSMET: False

# True/ False or Values allowed
# Metadata and Resource Use Constraint Code
# Note For RESTRICCODE - ALL items will be checked for.
RESTRICCODERES: ["copyright", "license"]
RESTRICCODEMET: ["copyright", "license"]

# True/ False or Values allowed
# Check Resource/Metadata Use Constraint Text.
RESOURCECON: True
METADATACON: True

#------------------------
# True/ False or Values allowed
# Extent Description
EXTENTDESCRIPTION: ["nzl", "NZ_MAINLAND_AND_CHATHAMS", "NONE"]
EXTENTBOUNDINGBOX: False

# True/ False or Values allowed
EXTENTTEMPORAL: False
EXTENTVERTICAL: False

#------------------------
# True/ False or Values allowed
SCALE: False

# True/ False or Values allowed
RESOLUTION: False

#------------------------
# True/ False or Values allowed
# Check Reference System Not None
REFERENCESYS1: False

# True/ False only allowed
# Check Reference System if Not None, is correct (Checking against CRS in API)
REFERENCESYS2: True

#------------------------
# True/ False or Values allowed
TITLE: True

# True/ False or Values allowed
ALTTITLE: False

# True/ False or Values allowed
ABSTRACT: True

# True/ False or Values allowed
PURPOSE: False

# True/ False or Values allowed
# Check Layer Status
STATUS: False

#------------------------
# True/ False or Values allowed
LINEAGE: True

#------------------------
# True/ False or Values allowed
LINKAGE: False

#------------------------
# True/ False or Values allowed
SPATIALREPRESENTATION: ['textTable']

#------------------------
# True/ False or Values allowed
TOPICCATEGORY: True

#------------------------
# True/ False or Values allowed
FID: True

#------------------------
# True/ False or Values allowed
MAINTENANCE: False
# True/ False or Values allowed
MAINTNEXTUPDATE: False

#------------------------
# True/ False or Values allowed
KEYWORD: False

#------------------------
# True/ False or Values allowed
# At Least One
KEYDATE: True

# Check Dates, are formatted correctly ie:
# YYYY, YYYY-MM or YYYY-MM-DD
# True/ False only allowed
DATEFORMAT: True

#------------------------
# True/ False only allowed
# Check for empty tags
EMPTYFORMAT: True

#-------------------------
# Default constraint Text fields - Not Included as part of Checks
# Must be formatted in a single line, to have the text show additional lines add '\n'.

# RCOPYRIGHT, MCOPYRIGHT - Resource/ Metadata use Copyright default Text
# RLICENSE, MLICENSE - Resource/ Metadata use License default Text

RCOPYRIGHT: 'Copyright of this work is owned by Land Information New Zealand.\n© LINZ'
MCOPYRIGHT: 'Copyright of this work is owned by Land Information New Zealand.\n© LINZ'

RLICENSE: 'Released by LINZ under Creative Commons Attribution 4.0 International (CC BY 4.0) with:\n\nFollowing Disclaimers: 1.\n##restrictions##\n\nFollowing Attribution:\n"Sourced from LINZ Data Service and licensed for reuse under the CC BY 4.0 license" For details see https://www.linz.govt.nz/data/licensing-and-using-data/attributing-linz-data'
MLICENSE: 'Released by LINZ under Creative Commons Attribution 4.0 International (CC BY 4.0) with:\n\nFollowing Attribution:\n"Sourced from the LINZ Data Service and licensed for reuse under the CC BY 4.0 License" For details see https://www.linz.govt.nz/data/licensing-and-using-data/attributing-linz-data'